spring:
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  communications:
    email:
      from: noreply@localhost.local

logging:
  level:
    pt.sanguept.communications: DEBUG
